services:
  musclecode-execution-worker-dev:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: musclecode-execution-worker-dev
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - APP_PORT=3002
      - NODE_ENV=development
    volumes:
      - ./src:/app/src  # Only mount the src directory for development
      - /app/node_modules  # Preserve container node_modules
      - /app/templates  # Preserve container templates and their node_modules
      - ./code:/app/code  # Bind mount for code execution
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_ADMIN
    working_dir: /app
    command: yarn start:dev

volumes:
  code-execution:
    name: musclecode-code-execution-dev 