apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: musclecode-prod

resources:
  - ../../base
  - ./secrets/sealed-app-secret.yaml
  - ./secrets/sealed-registry-secret.yaml

patches:
  - target:
      kind: Deployment
      name: musclecode-backend-execution-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod

  - target:
      kind: Service
      name: musclecode-backend-execution-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod

  - target:
      kind: VirtualService
      name: istio-musclecode-backend-execution-service-virtualservice
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod
      - op: replace
        path: /spec/hosts/0
        value: "execution-service.api.musclecode.devostack.com"

  - target:
      kind: ConfigMap
      name: musclecode-backend-execution-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod