---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials-execution-service
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgB4TQLNFzjriHVXTlfkjSpjxnXGb+hpcF1nzGLDadjRxJAtqxYUwY5BxdfXWQoNT1buEK4mFcyQrQ/MBmJ7RpL6dnKoBIC5lQCDeJguzqBjIQ8Un8vNVvGK4M0xJphgLr3dvMuDeEZOSpJE4yQUmIRACuYUwT89LBISdo7SNl3fegDeGmfKXDXUwmKcxf1FVLLNmvR4ilM8b26EaWFIPYwLc24usV3K6DYOkdtMaWvvcXe0dp0k4J+8e5h3lbKifNhNR2HvEZz1BP2VX6hdgcIU9w9J4xIVFiyzmYHdgBRmCSfmTyOeXW487X19zJyH7CAKqKQ9W/q6HufzzQ6wR9x7lgbw5p4nEZF1c+ivVmLdvKDe6dKJzbTVVUjGeWhfG7112Wuwqped/hseBrLpvpAhpkN+YsHgFL2JClOWo4zwJdgisVtGseCM8FQERLqZiofijm7iFo/atULx1EilzlSKwRXnmQYCJpjgY/r8iiZZq+u/sTcDmBDP9kM1NBXDBc+ZkxwVa5x/bGUvc3XHHFvEdiKA05Yyc7h3vdRkQmnpNFL5sq0FnM+ToF1g4ggL1/TMlcdQlsFjJcpO20VjSAt7XHswTAaurgkIzt9MGF7+qYSZhNDKTEIhSxcB1uHOq342uvsTI+aoJDJItHwRR6Br9gCER1dJvdmQqQkS4gCk1yhn25+5gLfl1Ih8/O5EadzVX3Ir4wz2h6o8vfNKcEV/QLqTBRp1lmYhVLxwLNb1EsW2HC+7Uxs44olw0FSZXaiocMvJf2mzByjyY4y/2/1UTBXvUTQ4FMILhiwvDL/zMFcLkGNlihSp+m83Kf7jmnpu2IJw6aaVKvyf6go5RmbJIkH7jePpJ+BVAbdbj2D9p7+5rgEA2o8j6CoewgmJj2KA7nz+dSt8AbAvhA6OK3yLsr5RHJuCTfio2g+9e81qvO+kVmUc
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials-execution-service
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
