---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCqZFJMVzGTe9CmMUEvfFEjrlYz3sqtq3RT0WIELT4vuxwY4BzTAEu0RT2IX15yezv1EVMVloqrAcDhwmpEGXkoPKxvUMuwwp4OFpqHrm43KFT79fEzq7qV/vvRSWIs0LcyjoAs9GYTzOYfsRj3hGVlV2WCxgMF/ETCOP3Sh6/6tPusvA1biCrme4R1CKJ2SJoeg9TIEBqUG8DPfbRbjK0Z04TCbENKOH0qzIQJDjvBm77XWvzthLTrHIQMHOKaHtvp9JkHk5KzGEucUzBqmzp5sWj2XHFb69wb20yZgDUhKdFsBOwLA+fuE+RvFhbZxIyfv4LNmS0KHgxaUAr4ZZmBg7tk7jNZ0eUv+47wmMNCxoIYxjsUV0baitPUO/inQiYcsBGTUCw+kykVgwi05+s8V8TgHIwgDn4pWKrvwH/Dh8/xD6V3yFa+AMvP2KhggZy0nWrtjl+YpX6N011KbQx+oxfEDRQa5mwn48efXKXT7IJqsMHMQwT2pIS3Df42OaT9my57VXVuIMHLEMzgX6F0i4x1uIp9HBTCV8UxHofjgRCUgKVA6/PBFpkWVnPTTuhU/dN2ohrTKmekeHnl73L9TcsGcNdrUQdRrNK88/+aNmbkI3i2qO7yMB6jPMzINXZdwslOqDgq2kr3nFzF+/ozvosQyS3IY4wmO7CaeI7Eq54DVZJRJgACN+yxVQR1E282O8dO01V2y2yfrsCHDx2CJnjOmcThscF2QUuhPOFYLJGPk+fqXD5ToaXM5OLs9UWwkjzRuZcQN3oHhpLfhOloMD7Mw6fMUBu4PdSPKvL2DNZo+pPTDLXEN9MkG5n4K/oY8nb451XBNMXJEsPUd/ZNt3O6acBHHo/WLIv6NJAaRx0GrH6y+E4eX7Ha7/aap5b7vUNw5wfvZ/duFcBgtLS8KvXwuBPw98D+ACgSkBN/cl9soMz0
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
