---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials-execution-service
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgDNnAfCvZEZ32F4ROtHJH0q0IUGmfSn/Imv7g+PW4iYjg0lGFzoEXwDBBqKCSUQOaklJVged1VAaarxCHAYhw5qlHq/lNpAKyEZ92XWLL+axCTCzdUVvVmd8FGSkyr5VfAOh4aCkJn16wyh6vWbsJ2EGHz6RTES2FnkEl4g0dW82i9V30Qm5CaueOxY4TossNrzrzsOd9TY2DmQ/eLlp1yEHUAxOhIM2K9rlmdIDrE5n0VqwVZzihDDs/KwsGLpw0Gz0EDruXt8Q4dU2rRy586RJxo3PfEs/QxUjgXBUn7+Htm4j4t7e43KfXpD8TRomgPCNPx1MjL8k7TmQMJXTchki38XZx6m/Q8LnGH+R36Ma69jtxZFBKc240vk7aEPtFUE5PtCqaz99yA/IuSpWcwyrQyc+ja3DC6TgQCBWAorPQxma3sZ2uwbBhmLwvpLJFk8iOsX8Txx/mcZlKH5zpVZQu9ZsJxjlxQegXxFDCpf6R4v6Di8MbH5+dOC4iTu/mr3zZ9VeH9AkAoq/rk/gLaaa76+7ZXZo52qNrdWX+rMCEFCRbRw/SXSDT90KNXd/XooIH7+TPbJwNSnMdhD7HpuzOuXXlaJQEoRXYnxSfty05x52IBgav+2hCFAk/sRE188ZkRv1PwtBcbfExRg0U0cLXPDGJHzl0xZ9rHUEgqldbiyLtmHc2Uu6NmQHQpHHrMVN5kfEaJOFBRhV+7Qx8Rkb5lFgb4h5/J1JobZybieRKobIIXyY1k3J0T5xYmXUE8S5dHLkdo2uDkENFYUn29IRPYciZK7tF/HQtqdYtjDn2VodAoyZHJmt/g3AAN+nxRp4OlyU3HHagIjgchDEenvqZDj5HATlzTSIgiVG15Zf2bRTMgmOWwFekiC8G/AZfbMolPhLhdI5zLTUzrxZMZ83O1pR9v13P3cFGsbos4NopS+HhAH
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials-execution-service
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
