---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials-execution-service
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCSNbsqP+494jrn6hW8K8L9ptormkCqE+xl71SS01LYafGL8qMQb9A5uiaiyRHeLTm3AgixeHmI8+JXQRniZwGe76QlR5nitu9rR7B8TH7TkdANikgR+bmAXCaYPkOVMOo08sWjN1SUl4fYKqOzrypEll7KP9YWZLUsQABzSVVuc6xFIWcwniO6sCP0D6bElVOmzKJY+0+YI3sQtFq5BFUKLKDW0MMDojcEA8z2i2UBXoFd0Y9Fjbu4pbdQ5JQisxHTa3Pw/X1ATeIePV9qwQzMEIL9i4O6/hLG7QDveKRI3mDHSdDoW494mGQvibgx+D1dKBXjuoUp9pOoIpdLAYXcrSN4U05Jzy/hlW5xnrq49HVKCPxaJN1MAmLyOc2mAxTI4Ke35clEZMGTzZNP2uthMZI4TamVliAMD1oxTV85miCq9CfN/LFHnrdMQ4ZjrgMLzjNILAPAPCwG6KD34GXYlI5MWdu2fYP7PhcBmE8oGysb/0wDmRjn8OqiSMwY+R23jF30VmHTlEFsY4EUmnnfcc//VV5YVJSyMYCkpK/+XJXsxzsmNwVRftzfy6e8bY8mtkdVD0hRRAMslGSDxZypW2VAlRvnRMPGC7jCF9SS9c84t0g5uOcLlDD1BrGGqg1Gbqpqxzh7qWw9TGfDOdrEfv1Rw9qf3uxoLBP1n4n3IAoVWRbCdmJ2dJ+ftC0wXB0hlUBIzwODbNncIEu/Isgo1QhEyNk4oc8mY3PXWD+vY5Hm3ROrGKo4kI44eQOR0FcB4F7unXmSqRWk/y4UXBDx7yUrZp6V2M58RZ4Dyd3cF0flNJ4xjekGIm3PqGU4BB0A4Kbub8ttZnrTZXq7mP586ATg5rDcvmmbFXpbI3Kr2ncA9cDJpYFXrlQELm1dpkQRdV7D70pOIGvepOKOWDj3z9+6VGEDmF3lx0Z3lANzmdVght7h
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials-execution-service
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
