---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials-execution-service
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBDdPa8jhWdZCzHDT4bd2RYiriUY2SegKOFjuMr08fLKsgbHuYJ54D/U8ok9coWOJ0G8oCy2/T5WZU2IS4d56LSJBAbQfXUbN5KiyIp/3z4yajcDOkZzChndm/LjQet4OWayuC2W6AWBrvhbe+UbW++CLuEHU7ZDkj810a4sG20QWPMb+kPDO1U5oXyunkkNgp6LJOxPib/rxrh09t8YbBYMl0DZVY7h4fqFY8Yvx5hNRTv+YbA7CJ2P6tAxcjJ78/p+KzUUhNTldgB3TZ6BKpK24us4mcPJzUvvSV6L7J2WWZTgw+DDhrfzATcRR9tbe4Tt/q2EUW8ooFENnFHO/qi1Oc5rNLlR0R83BD85MsSiPDIqZ4KgQgoW3kbbmVCOb3KYkGiSJ73SODAe5e323O1hePfBFEXc1fgj6rrD3mTKXQtSRvaGssXVLJ/nzbxjFJ6FWNghgqg8mPizQ5jnpYYsxJleP4VgTxWQ4h39Nnr29g4Pl0Lnzgp14mnblydda/ffRIO7SJaBy0poXVclrMFBgL2VaJYq+oBSE6KmFDidJduE2sIFiqFjsMvNwDBLsFLpOMsr1nlpzzM76vot30QI/1UW8ASUzzQmcOtbjCDjutgc4WLJC2rhmTfwehSmmVUj04tcnRLWitBwaidWmYIgW4arYLQSkSHyg+r31aEkLN42IESB/p9yd2+GhDkfit2kD8/jtoZVWKs1gM7B9oWRQFiZag2+Kg3bVqx0TagAGKBnv10RpBpZDVbJj1wtayjySvtgMbCkn8WzdbaZDfpFm0gtlR7MnXIBeCxDL9ZwEqFLGvqQBKvFFnqHKRLr4+3skY3ArTST5H4rg47BVZF7AfBdYG5YjGnx+FwWiWUc3oPawxZWGsZohXUcW5xBCo3/pVTjYY7VGqqZpx4JoZ1kxXua4rjTucJ5cnbZeNs9mecCPuJ
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials-execution-service
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
