---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAvbIzQ/DP2FCeG8+9/CRjUVG27Bag9yW+0+K5Z7VLx5ro8MXbEA0EQeuNnUdizXDSOtSRcG9/y/SlzozzOT7B+4Apgqr/H3AdU0omrjo5szzsCWUOUp9DBu/CGMnd0vxYMUkBy0nc8VP3iRDT6q09CM0Ll2tNPyAdWo3lgTG/mbdfx8CFBjq7j6YuqTH1Zikg2kKg8alCmLiCpjOYRTrt+Ly++995pFmsePcod4LXYzDo9pSVnQ79DOFUSwOKigIyQAdjawDePM9tWhPPW3I3WaeGYAsaHb1Ioml5z9k4jcGisFw0K0fb0cOlQjHcR0eC778+m/xGMjRufqf3pM8SVIMQsd0VlKI3GPrDhFYR0sez95n6kavQfKMIv2hISxP8deAf8Tgte6+hDPgwqU4S43RilEQ1wEdyylXtbYVy+XGWZBPk5SBsXnKhMRwK3vJ75QAPT1XGIEWEnVtKl0k1C/EPwoPp3ZlzXz8nig5aIXV1kPzRuYrdDp5d67LDnkZAKi5B4ZlOIwQLJQuk3JKRxGcCHZYrrU4YSzJkAVCR28O0kltjj+ff1DVtWsjZTdvnmaeqcCVpqA85zCucGMYKqj7HGFJbsY1QzVjcRMYwk82NEyYmndRXbVLw35QshDR/dK7cRXxSoDdQJ2PF1OPAOGIIl8Y7ldQu5BYI9iDKpPdRt+OIdMf8Y1qLZDLmbKkeqP4R6IlLQ8HlbgOAuJ6rEA1D3xQ6BxMcyNYNZqBDpq9PQo89H9l+DjSkTFvmIko4QO1eO54jUAZbvVoXkbjf8UDO0p1a0gfnSWuAMp9yXWWHWOl9pq3jdP+KyETFMnWs8IRFvtOQ6JHGMwzoQeuz/K9uG/jrcgtVmB0iSXu8GVTQJpTE8Hto83iAeYRjn6kBGTDdlZIgb+C4Y4gmgM5LnP8R1ncr3Z5CCMwvgWF7oalFGsfN6
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
