apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dailykatas
  name: deployment-role
rules:
- apiGroups: [""]
  resources: ["services", "pods", secrets]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
