apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-rolebinding
  namespace: dailykatas
subjects:
- kind: ServiceAccount
  name: deployment-sa
  namespace: dailykatas
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io
