apiVersion: v1
kind: ConfigMap
metadata:
  name: musclecode-execution-worker-config
  namespace: musclecode
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  # Application Configuration
  APP_NAME: "musclecode-backend-execution-service"
  NODE_ENV: "production"
  APP_PORT: "3000"

  # Debug Configuration
  DEBUG_MODE: "true"

  # Logging Configuration
  LOG_LEVEL: "debug"
  LOG_BATCH_SIZE: "100"
  FLUSH_INTERVAL: "5000"
  
  # Observability Endpoints
  LOG_ENDPOINT: "https://otel.devostack.com/v1/logs"
  TRACE_ENDPOINT: "https://otel.devostack.com/v1/traces"
  
  # Kubernetes Cluster Information
  K8S_CLUSTER_NAME: "default" # This should be overridden in overlays
  