apiVersion: apps/v1
kind: Deployment
metadata:
  name: musclecode-backend-execution-service
  annotations:
    devostack.com/image-sha: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musclecode-backend-execution-service
  template:
    metadata:
      labels:
        app: musclecode-backend-execution-service
    spec:
      imagePullSecrets:
        - name: registry-credentials-execution-service
      containers:
        - name: musclecode-backend-execution-service
          image: harbor.devostack.com/musclecode/musclecode-backend-execution-service:latest
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 9229
              name: debug
          envFrom:
            - secretRef:
                name: musclecode-backend-execution-service-secrets
            - configMapRef:
                name: musclecode-execution-worker-config
          env:
            - name: DEBUG_MODE
              valueFrom:
                configMapKeyRef:
                  name: musclecode-execution-worker-config
                  key: DEBUG_MODE
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['devostack.com/image-sha']
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: code-execution
              mountPath: /app/code
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: code-execution
          emptyDir: {}
        - name: tmp
          emptyDir: {}
