apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml
- configmap.yaml
commonLabels:
  app.kubernetes.io/name: musclecode-backend-execution-service
  app.kubernetes.io/part-of: musclecode

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: musclecode-backend-execution-service
    spec:
      template:
        metadata:
          annotations:
            image-sha: b50c8aedc61f17ea24f1830f738e8079ff724be7
  target:
    kind: Deployment
    name: musclecode-backend-execution-service

images:
- name: harbor.devostack.com/musclecode/musclecode-backend-execution-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-execution-service
  newTag: b50c8aedc61f17ea24f1830f738e8079ff724be7
