apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-execution-service
  app.kubernetes.io/part-of: musclecode


images:
- name: harbor.devostack.com/musclecode/musclecode-backend-execution-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-execution-service
  newTag: 07378ec7a72a9d03a78cd311e754db4dd051ba77
commonAnnotations:
  image-sha: 67e9e107b614c05fce6fa3b44ed787c7ee70e14c
