apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml
- configmap.yaml
commonLabels:
  app.kubernetes.io/name: musclecode-backend-execution-service
  app.kubernetes.io/part-of: musclecode


images:
- name: harbor.devostack.com/musclecode/musclecode-backend-execution-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-execution-service
  newTag: 45b4bf82fec2194647e38daa8a2e75ff36e1330a
commonAnnotations:
  image-sha: 67e9e107b614c05fce6fa3b44ed787c7ee70e14c
